name: bugzilla2github
steps:
  -
    input:
      -
        name: "Bugzilla"
        oslc: 'http://localhost:5000/service/serviceProviders/catalog'
        trs: 'http://localhost:8085/OSLC4JBugzilla/services/trs'
        user: 'admin'
        password: 'adminpass'
    output:
      -
        name: "Github"
        oslc: 'http://localhost:5001/service/catalog'
        trs: 'http://localhost:5001/service/trackedResourceSet'
        user: ''
        password: ''
    rules:
      - 'bug_issue_create.n3'
      - 'bug_issue_update.n3'