version: '3'

services:
  oslc-ewe_gateway:
    build: .
    volumes:
      - ./example:/example
    network_mode: "host"
  
  fuseki:
    image: stain/jena-fuseki
    container_name: fusekiroi
    ports:
      - "3030:3030"
    volumes:
    - ./fuseki:/fuseki
    environment:
      - ADMIN_PASSWORD=fusekiadmin