version: '3'

services:
  github_adapter:
    image: oslcapi
    build:
      context: ./github-oslc_adapter
    container_name: github-adapter
    command: flask run -h 0.0.0.0
    env_file:
      - ./github-oslc_adapter/.flaskenv
      - ./github-oslc_adapter/.env
    environment:
      - DATABASE_URI=sqlite:////db/oslcapi.db
    volumes:
      - ./github-oslc_adapter/oslcapi:/code/oslcapi
      - ./github-oslc_adapter/db/:/db/
    ports:
      - "5001:5000"

  bugzilla_adapter:
    image: oslcapi
    build:
      context: ./bugzilla-oslc_adapter
    container_name: bugzilla-adapter
    ports:
      - "5000:5000"
    command: flask run -h 0.0.0.0
    env_file:
      - ./bugzilla-oslc_adapter/.flaskenv
      - ./bugzilla-oslc_adapter/.env
    environment:
      - DATABASE_URI=sqlite:////db/oslcapi.db
      - BUGZILLA_URL=$BUGZILLA_URL
      - BUGZILLA_API_KEY=$BUGZILLA_API_KEY
    volumes:
      - ./bugzilla-oslc_adapter/oslcapi:/code/oslcapi
      - ./bugzilla-oslc_adapter/db/:/db/

  bugzilla:
    image: bugzilla/bugzilla-dev
    container_name: bugzilla
    ports:
      - 80:80
      - 5900:5900
    
  bugzilla-trs:
    image: maven:3.3-jdk-8
    container_name: bugzilla-trs
    command: mvn clean jetty:run
    volumes:
      - ./bugzilla-trs:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    ports:
      - 8085:8085
    depends_on:
      - bugzilla